import Link from "next/link";
import { buildWhatsAppUrl } from "../lib/whatsapp";
import { posts } from "../lib/blog";

export default function Home() {
  const prevencion = [
    ["Regularización Legal", "Diagnóstico y apoyo documental para mejorar el cumplimiento en Seguridad y Salud en el Trabajo."],
    ["Matrices de Riesgos", "Identificación de peligros, evaluación de riesgos y definición de controles preventivos."],
    ["Informes de Gestión", "Reportes ejecutivos, indicadores y seguimiento para gerencias, comités y sucursales."],
    ["Capacitaciones", "Charlas y formaciones en temas críticos de prevención de riesgos laborales."],
    ["Inducción Persona Nueva", "Apoyo para inducciones de trabajadores nuevos, registros y respaldos."],
    ["Comité Paritario", "Acompañamiento para constitución, reuniones, actas, programas y funcionamiento CPHS."]
  ];
  const masoterapia = [
    ["Masaje Relajante", "60 minutos", "$25.000 CLP", false],
    ["Descontracturante", "60 minutos", "$30.000 CLP", true],
    ["Masaje Mixto", "90 minutos", "$40.000 CLP", false],
    ["Piedras Calientes", "75 minutos", "$38.000 CLP", false],
    ["Piernas Cansadas", "45 minutos", "$22.000 CLP", false],
    ["Masaje Deportivo", "60 minutos", "$35.000 CLP", false]
  ];
  const process = [["1","Diagnóstico","Revisamos necesidad, contexto y objetivo."],["2","Plan de acción","Definimos alcance, horario y entregable."],["3","Ejecución","Realizamos asesoría, informe o atención."],["4","Seguimiento","La reserva queda registrada para gestión."]];
  return (
    <main>
      <section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Servicios profesionales en Chile</div><h1>Prevención de Riesgos y Masoterapia Profesional</h1><p>Una plataforma simple para contratar servicios de gestión preventiva para empresas y sesiones de bienestar corporal con agenda online, recordatorios y confirmación por WhatsApp.</p><div className="badge-list"><span className="badge">SEO Local</span><span className="badge">Blog</span><span className="badge">Testimonios</span><span className="badge">Dashboard Admin</span><span className="badge">Galería</span></div><p style={{marginTop:28}}><Link className="btn" href="/agenda-prevencion">Agendar Prevención</Link>{" "}<Link className="btn secondary" href="/agenda-masoterapia">Agendar Masoterapia</Link></p></div><div className="hero-card"><div className="image-band"><div className="eyebrow" style={{color:"#ccfbf1"}}>Etapa 5A</div><h2>Web comercial lista para captar clientes</h2><p>Blog, SEO local, testimonios, galería y dashboard administrativo.</p></div></div></div></section>
      <section className="section alt"><div className="container"><div className="grid-4"><div className="kpi"><strong>2</strong><span>Áreas profesionales</span></div><div className="kpi"><strong>14</strong><span>Días visibles en agenda</span></div><div className="kpi"><strong>5</strong><span>Artículos SEO</span></div><div className="kpi"><strong>6</strong><span>Landings locales</span></div></div></div></section>
      <section className="section soft"><div className="container"><div className="eyebrow">Soluciones según necesidad</div><h2>¿Qué tipo de servicio necesitas?</h2><div className="grid-2" style={{marginTop:28}}><div className="feature-card"><h3>Para empresas</h3><p>Apoyo en cumplimiento legal, matrices de riesgos, informes, capacitaciones, inducciones y Comités Paritarios.</p><ul className="list"><li>Gestión documental preventiva.</li><li>Preparación para fiscalizaciones.</li><li>Capacitaciones e inducciones.</li><li>Diagnóstico de brechas SSO.</li></ul><Link className="btn" href="/agenda-prevencion">Agendar diagnóstico</Link></div><div className="feature-card"><h3>Para personas</h3><p>Sesiones de masoterapia para relajación, descarga muscular, recuperación corporal y bienestar físico.</p><ul className="list"><li>Masajes relajantes.</li><li>Descontracturantes.</li><li>Piedras calientes.</li><li>Piernas cansadas y masaje mixto.</li></ul><Link className="btn secondary" href="/agenda-masoterapia">Reservar sesión</Link></div></div></div></section>
      <section className="section"><div className="container"><div className="eyebrow">Área empresas</div><h2>Servicios de Prevención de Riesgos</h2><p>Soluciones orientadas a cumplimiento legal, gestión documental, capacitación y control preventivo.</p><div className="grid-3" style={{marginTop:28}}>{prevencion.map(([title,text])=><div className="card" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section className="section dark"><div className="container"><div className="eyebrow">Proceso de trabajo</div><h2>Una experiencia clara de principio a fin</h2><div className="grid-4" style={{marginTop:28}}>{process.map(([num,title,text])=><div className="card process-step" key={num}><div className="step-number">{num}</div><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
      <section className="section soft"><div className="container"><div className="eyebrow">Área bienestar</div><h2>Servicios de Masoterapia</h2><div className="grid-3" style={{marginTop:28}}>{masoterapia.map(([name,duration,price,highlight])=><div className={highlight?"price-card highlight":"price-card"} key={String(name)}>{highlight&&<span className="badge">Más solicitado</span>}<h3>{name}</h3><p>{duration}</p><div className="price">{price}</div></div>)}</div><div className="cta"><h2>Reserva tu sesión</h2><p>Selecciona el servicio, fecha y horario disponible desde la agenda online.</p><Link className="btn secondary" href="/agenda-masoterapia">Agendar Masoterapia</Link></div></div></section>
      <section className="section alt"><div className="container"><div className="eyebrow">Blog profesional</div><h2>Últimos artículos</h2><div className="grid-3" style={{marginTop:28}}>{posts.slice(0,3).map(post=><Link className="card" key={post.slug} href={`/blog/${post.slug}`}><span className="badge">{post.category}</span><h3>{post.title}</h3><p>{post.excerpt}</p></Link>)}</div><p style={{marginTop:24}}><Link className="btn dark" href="/blog">Ver blog completo</Link>{" "}<Link className="btn secondary" href="/newsletter">Suscribirme al newsletter</Link></p></div></section>
      <section className="section soft"><div className="container"><div className="eyebrow">Confianza</div><h2>Testimonios destacados</h2><div className="grid-2" style={{marginTop:28}}><div className="card"><h3>Empresa de Servicios</h3><p>“Nos ayudó a ordenar documentación preventiva y mejorar la gestión interna.”</p><span className="badge">Prevención</span></div><div className="card"><h3>Cliente Particular</h3><p>“Atención muy profesional, clara y cuidadosa. Excelente sesión de masoterapia.”</p><span className="badge">Masoterapia</span></div></div></div></section>
      <section className="section alt"><div className="container"><div className="cta"><h2>¿Necesitas ayuda profesional?</h2><p>Agenda un servicio de prevención, reserva una sesión de masoterapia o escríbeme por WhatsApp.</p><Link className="btn" href="/agenda-prevencion">Agendar Prevención</Link>{" "}<Link className="btn secondary" href="/agenda-masoterapia">Agendar Masoterapia</Link>{" "}<a className="btn whatsapp" href={buildWhatsAppUrl("Hola, quiero solicitar información sobre tus servicios profesionales.")} target="_blank" rel="noopener noreferrer">Contactar por WhatsApp</a></div></div></section>
    </main>
  );
}
